### Get token
POST http://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic risk 33162EB2-9B2E-4E7A-AE67-D40CE7DE9AB7

grant_type=client_credentials&scope=read_users


### Get users
GET http://localhost:5001/api/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjBBMzg4RDJCNDVDMDc4NjM3MjEwOTAyQ0U3MUUxMzJDIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJuYmYiOjE3MzIxMTgzNDgsImlhdCI6MTczMjExODM0OCwiZXhwIjoxNzMyMTIxOTQ4LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEvcmVzb3VyY2VzIiwic2NvcGUiOlsicmVhZF91c2VycyJdLCJjbGllbnRfaWQiOiJyaXNrIiwianRpIjoiNTBGOTMzMUE2N0VFOTA2MEZBREMzRTgzOEQyOTZEMDIifQ.qAc7T30GsuinnLlezVBKDcFTtdACw7D0U74YHRDYYip4YOAHGNyn-cXnrowEDjngJoVV_CF0wxnXI3JkAAZGYxJxKeOErpqXLaK5N_ccC4LehbrbijpuorIqnvMTeKgcKRlqr2s-8btl1twbqqb6as0ED3xTGehRP1tDcYr16NvGiK2vmfaVJuZWY8N7rRVUSOEgrUdvY2wpc3QNz9OcB3BN3zxWSBGyFId67h08RYmOH48j7LdqEktV_88anJcv9c_hpcHW5lhtpOBc1HXNx9hrfCq4_pp3zoWyF6bcY5PfOicIu23dN8n3n_NQLpc5tUiFz6_1FJo19i6lFWJDOA
